doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        dql:
            string_functions:
                JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
                JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains

        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            App:
#                is_bundle: false
#                type: attribute
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
            Geonames:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Geonames/Entity'
                prefix: 'App\Domain\Geonames\Entity'
                alias: Geonames
            Map:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Map/Entity'
                prefix: 'App\Domain\Map\Entity'
                alias: Map
            Article:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Article/Entity'
                prefix: 'App\Domain\Article\Entity'
                alias: Article
            Fielddefinition:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Fielddefinition/Entity'
                prefix: 'App\Domain\Fielddefinition\Entity'
                alias: Fielddefinition
            Area:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Area/Entity'
                prefix: 'App\Domain\Area\Entity'
                alias: Area
            Organisation:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Organisation/Entity'
                prefix: 'App\Domain\Organisation\Entity'
                alias: Organisation
            Person:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Person/Entity'
                prefix: 'App\Domain\Person\Entity'
                alias: Person
            Specie:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Specie/Entity'
                prefix: 'App\Domain\Specie\Entity'
                alias: Specie
            Mapserie:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Mapserie/Entity'
                prefix: 'App\Domain\Mapserie\Entity'
                alias: Mapserie
            Link:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/Link/Entity'
                prefix: 'App\Domain\Link\Entity'
                alias: Link
            SystemParameter:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain/SystemParameter/Entity'
                prefix: 'App\Domain\SystemParameter\Entity'
                alias: SystemParameter
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
