doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        dql:
            string_functions:
                JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
                JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains

        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            App:
#                is_bundle: false
#                type: attribute
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
            Geonames:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Geonames/Domain/Entity'
                prefix: 'App\Geonames\Domain\Entity'
                alias: Geonames
            Map:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Map/Domain/Entity'
                prefix: 'App\Map\Domain\Entity'
                alias: Map
            Article:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Article/Domain/Entity'
                prefix: 'App\Article\Domain\Entity'
                alias: Article
            Fielddefinition:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Fielddefinition/Domain/Entity'
                prefix: 'App\Fielddefinition\Domain\Entity'
                alias: Fielddefinition
            Area:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Area/Domain/Entity'
                prefix: 'App\Area\Domain\Entity'
                alias: Area
            Organisation:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Organisation/Domain/Entity'
                prefix: 'App\Organisation\Domain\Entity'
                alias: Organisation
            Person:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Person/Domain/Entity'
                prefix: 'App\Person\Domain\Entity'
                alias: Person
            Specie:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Specie/Domain/Entity'
                prefix: 'App\Specie\Domain\Entity'
                alias: Specie
            Mapserie:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Mapserie/Domain/Entity'
                prefix: 'App\Mapserie\Domain\Entity'
                alias: Mapserie
            Link:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Link/Domain/Entity'
                prefix: 'App\Link\Domain\Entity'
                alias: Link
            SystemParameter:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/SystemParameter/Domain/Entity'
                prefix: 'App\SystemParameter\Domain\Entity'
                alias: SystemParameter

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
